### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [trichimtrich/pysockssl#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.2. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary pysockssl -w /tmp/ext pysockssl==0.2
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting pysockssl==0.2
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/847/cbbcee474f65c/pysockssl-0.2.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-mx6dbiad/pysockssl/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-mx6dbiad/pysockssl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-mx6dbiad/pysockssl/pip-egg-info
         cwd: /tmp/pip-wheel-mx6dbiad/pysockssl/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-mx6dbiad/pysockssl/setup.py", line 17, in <module>
        with open(os.path.join(here, 'requirements.txt'), 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-mx6dbiad/pysockssl/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by trichimtrich** [comment]
Hi, can you make a pull request for that manifest. thank you.
